# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=6)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('news_short', models.TextField(blank=True)),
                ('news_url', models.URLField(unique=True)),
            ],
        ),
    ]
